input:
    n_threads: 20
    in_fasta: /lustre/BIF/nobackup/leuw006/uhgp-50/uhgp-50.faa
    orphan_db: '/lustre/BIF/nobackup/leuw006/scripts/test.fa'
    ml_model: '/lustre/BIF/nobackup/leuw006/scripts/uhgp_simulations_300000/machine_learning/ml_models/combined_bayesian.sav'

#parameters (the paramaters must always be specified in a list even if only 1 value is needed except for the size of the subsets)
parameters:
    evalues: [0.001, 1]

#I would advice to put them into a seperate directory.
#Since you don't want it to overwrite the existing directories.
output_directories:
    out_diamond: diamond_results
    out_orphan: filtered_orphans
    out_machine_learning: machine_learning